---
title: "SDG 10.C"
author: "Emily Robinson, Nathanael Sheehan, Owain Harris"
date: "05/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Data analysis

The analysis presented in this report addresses an underrepresented understanding of research and dialogue on global remittance corridors and their effect on the global economic climate. Through following an anti naturalist methodology, our analysis does not seek to explain the social human phenomenon of migrant capital exchange simply through the causal dependence of social reality representation, nor does it wish to exploit the privacy concerns of highly aggregated data which in its purest form is tremendously sensitive, instead, the analysis aims to build a dialogue around climate vulnerable countries and their digital manifestation in open data from the private sector, and the impacts this has on the Sustainable Development Goals policy framework. 

As previously stated, there are two components of SDG 10.C, as delineated in the SDG metadata, the first component states “transaction costs for migrant remittances should be 3% or less by 2030”. Here, a transaction is defined as “Global average total cost of sending $200 (or equivalent in local sending currency) and expressed as % of amount sent” . The second component is to eliminate corridors “where cost is 5% or higher”, meaning that it should be possible for remittance senders to send capital to the “beneficiary for an average cost of 5% or less of the amount sent”.

